// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var RemainingSpaceBar$ReactTemplate = require("./RemainingSpaceBar.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, RemainingSpaceBar$ReactTemplate.make(/* array */[])), "reason");

/*  Not a pure module */
